### ISSUE TITLE
conv3d with empty kernel_map

### ISSUE THREAD

**Issue by cslxiao** [mit-han-lab/torchsparse#16]
Applying convolution transpose with conv3d sometimes returns an error due to the empty of kernel_map.
The reason is that [sparseconv_op](https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/functional/sparseconv.py#L212) is called without checking kernel_map is empty or not.

**Comment by zhijian-liu** [comment]
Thanks for pointing this out! I have created a PR for this issue.

**Comment by zhijian-liu** [comment]
@cslxiao, could you please install the latest version to see whether the issue has been resolved.

**Comment by cslxiao** [comment]
@zhijian-liu, good jod! But I think the bug is still there.
in the code:
```python
        # do upsample
        original_stride = int(cur_stride / stride)
        kernel_map = inputs.kernel_maps.get(
            'k%s_os%d_s%d_d%d' % (ks, original_stride, stride, dilation), None)
        output_features = sparseconv_op(features, kernel, kernel_map[0],
                                        kernel_map[1], kernel_map[2],
                                        transpose)
 
```
the error occurs at calling of **sparseconv_op** with **kernel_map** = None, because the kernel_maps of the input tensor doesn't necessarily contain the kernel_map required at the step when the network is not center-symmetric with regards to kernel_size, dilation setting.

**Comment by zhijian-liu** [comment]
Hi @cslxiao, thanks for the information. Could you please provide me with a minimal example to reproduce this? Thanks!

**Comment by cslxiao** [comment]
Hi, @zhijian-liu 
take the modified minkunet in repo [e3d](https://github.com/mit-han-lab/torchsparse) as an example,
```python

class DilatedMinkUNet(MinkUNet):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        cr = kwargs.get('cr', 1.0)
        dilation = kwargs.get('dilation', [1, 1, 1, 2, 2, 1, 1, 1])
        cs = [32, 32, 64, 128, 256, 256, 128, 96, 96]
        cs = [int(cr * x) for x in cs]
        self.cs = cs
        self.run_up = kwargs.get('run_up', True)
        self.output_feat = kwargs.get('output_feat', False)
        
        self.stem = nn.Sequential(
            spnn.Conv3d(4, cs[0], kernel_size=3, stride=1),
            spnn.BatchNorm(cs[0]), spnn.ReLU(True),
            spnn.Conv3d(cs[0], cs[0], kernel_size=3, stride=1),
            spnn.BatchNorm(cs[0]), spnn.ReLU(True))

        self.stage1 = nn.Sequential(
            BasicConvolutionBlock(cs[0], cs[0], ks=2, stride=2, dilation=dilation[0]),
            ResidualBlock(cs[0], cs[1], ks=3, stride=1, dilation=dilation[0]),
            ResidualBlock(cs[1], cs[1], ks=3, stride=1, dilation=dilation[0]),
        )

        self.stage2 = nn.Sequential(
            BasicConvolutionBlock(cs[1], cs[1], ks=2, stride=2, dilation=dilation[1]),
            ResidualBlock(cs[1], cs[2], ks=3, stride=1, dilation=dilation[1]),
            ResidualBlock(cs[2], cs[2], ks=3, stride=1, dilation=dilation[1]),
        )

        self.stage3 = nn.Sequential(
            BasicConvolutionBlock(cs[2], cs[2], ks=2, stride=2, dilation=dilation[2]),
            ResidualBlock(cs[2], cs[3], ks=3, stride=1, dilation=dilation[2]),
            ResidualBlock(cs[3], cs[3], ks=3, stride=1, dilation=dilation[2]),
        )

        self.stage4 = nn.Sequential(
            BasicConvolutionBlock(cs[3], cs[3], ks=2, stride=2, dilation=dilation[3]),
            ResidualBlock(cs[3], cs[4], ks=3, stride=1, dilation=dilation[3]),
            ResidualBlock(cs[4], cs[4], ks=3, stride=1, dilation=dilation[3]),
        )

        self.up1 = nn.ModuleList([
            BasicDeconvolutionBlock(cs[4], cs[5], ks=2, stride=2, dilation=dilation[4]),
            nn.Sequential(
                ResidualBlock(cs[5] + cs[3], cs[5], ks=3, stride=1, dilation=dilation[4]),
                ResidualBlock(cs[5], cs[5], ks=3, stride=1, dilation=dilation[4]),
            )
        ])

        self.up2 = nn.ModuleList([
            BasicDeconvolutionBlock(cs[5], cs[6], ks=2, stride=2, dilation=dilation[5]),
            nn.Sequential(
                ResidualBlock(cs[6] + cs[2], cs[6], ks=3, stride=1, dilation=dilation[5]),
                ResidualBlock(cs[6], cs[6], ks=3, stride=1, dilation=dilation[5]),
            )
        ])

        self.up3 = nn.ModuleList([
            BasicDeconvolutionBlock(cs[6], cs[7], ks=2, stride=2, dilation=dilation[6]),
            nn.Sequential(
                ResidualBlock(cs[7] + cs[1], cs[7], ks=3, stride=1, dilation=dilation[6]),
                ResidualBlock(cs[7], cs[7], ks=3, stride=1, dilation=dilation[6]),
            )
        ])

        self.up4 = nn.ModuleList([
            BasicDeconvolutionBlock(cs[7], cs[8], ks=2, stride=2, dilation=dilation[7]),
            nn.Sequential(
                ResidualBlock(cs[8] + cs[0], cs[8], ks=3, stride=1, dilation=dilation[7]),
                ResidualBlock(cs[8], cs[8], ks=3, stride=1, dilation=dilation[7]),
            )
        ])
```
symmetric dilation parameters like  _dilation: [1, 1, 1, 2, 2, 1, 1, 1]_ or  _dilation: [1, 2, 2, 2, 2, 2, 2, 1]_ is ok.
But asymmetric  dilation parameters will cause the aforementioned error,
such as  _dilation: [1, 1, 1, 1, 1, 1, 1, 2]_.

**Comment by CurryYuan** [comment]
Same question here. Do you have the plan to support directly inverse conv3d?

**Comment by zhijian-liu** [comment]
I think what you need here is a generative sparse deconvolution. This is a bit different from what we have implemented now. We will investigate this in more details.

**Comment by noahstier** [comment]
I am still having this issue with v1.4.0

```
import torch

import torchsparse
import torchsparse.nn

feat_depth = 64

coords = torch.zeros((0, 4), dtype=torch.int32, device='cuda')
feats = torch.zeros((0, feat_depth), dtype=torch.float32, device='cuda')
t = torchsparse.SparseTensor(feats, coords)

conv = torchsparse.nn.Conv3d(feat_depth, feat_depth, kernel_size=3, bias=False)

conv(t)
```

`RuntimeError: CUDA error: invalid configuration argument`

**Comment by resuly** [comment]
I think I got the same issue here. Is this related to [generalized Sparse Tensor](https://github.com/NVIDIA/MinkowskiEngine/issues/316#issuecomment-784221232)?
```python
/tmp/ipykernel_27426/3796938854.py in forward(self, x)
    198         x = to_sparse(x)
    199 
--> 200         x0 = self.stem(x)
    201         x1 = self.stage1(x0)
    202         x2 = self.stage2(x1)

~/.conda/envs/torchsparse/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/.conda/envs/torchsparse/lib/python3.8/site-packages/torch/nn/modules/container.py in forward(self, input)
    137     def forward(self, input):
    138         for module in self:
--> 139             input = module(input)
    140         return input
    141 

~/.conda/envs/torchsparse/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/.conda/envs/torchsparse/lib/python3.8/site-packages/torchsparse-1.4.0-py3.8-linux-x86_64.egg/torchsparse/nn/modules/conv.py in forward(self, input)
     64 
     65     def forward(self, input: SparseTensor) -> SparseTensor:
---> 66         return F.conv3d(input,
     67                         self.kernel,
     68                         kernel_size=self.kernel_size,

~/.conda/envs/torchsparse/lib/python3.8/site-packages/torchsparse-1.4.0-py3.8-linux-x86_64.egg/torchsparse/nn/functional/conv.py in conv3d(input, weight, kernel_size, bias, stride, dilation, transposed)
    121                                         input.stride)
    122             queries = F.sphash(coords, offsets)
--> 123             results = F.sphashquery(queries, references)
    124 
    125             nbsizes = torch.sum(results != -1, dim=1)

~/.conda/envs/torchsparse/lib/python3.8/site-packages/torchsparse-1.4.0-py3.8-linux-x86_64.egg/torchsparse/nn/functional/query.py in sphashquery(queries, references)
     19 
     20     if queries.device.type == 'cuda':
---> 21         output = torchsparse.backend.hash_query_cuda(queries, references,
     22                                                      indices)
     23     elif queries.device.type == 'cpu':

RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by zhijian-liu** [comment]
@resuly, could you please check the shape of `x` (both `coords` and `feats`) before the line of `x0 = self.stem(x)` (at L200)?

**Comment by Microslargh** [comment]
I Can't install this repo .........
please help me 
running build_ext
building 'torchsparse.backend' extension
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/torchsparse
creating build/temp.linux-x86_64-3.8/torchsparse/backend
creating build/temp.linux-x86_64-3.8/torchsparse/backend/others
creating build/temp.linux-x86_64-3.8/torchsparse/backend/convolution
creating build/temp.linux-x86_64-3.8/torchsparse/backend/devoxelize
creating build/temp.linux-x86_64-3.8/torchsparse/backend/hashmap
creating build/temp.linux-x86_64-3.8/torchsparse/backend/hash
creating build/temp.linux-x86_64-3.8/torchsparse/backend/voxelize
gcc -pthread -B /home/xie/anaconda3/envs/pytorch/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xie/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/home/xie/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/xie/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/home/xie/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.2/include -I/home/xie/anaconda3/envs/pytorch/include/python3.8 -c torchsparse/backend/pybind_cuda.cpp -o build/temp.linux-x86_64-3.8/torchsparse/backend/pybind_cuda.o -g -O3 -fopenmp -lgomp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda-11.2/bin/nvcc -I/home/xie/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -I/home/xie/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/xie/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -I/home/xie/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.2/include -I/home/xie/anaconda3/envs/pytorch/include/python3.8 -c torchsparse/backend/others/count_cuda.cu -o build/temp.linux-x86_64-3.8/torchsparse/backend/others/count_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=backend -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/usr/include/c++/10/chrono: In substitution of ‘template<class _Rep, class _Period> template<class _Period2> using __is_harmonic = std::__bool_constant<(std::ratio<((_Period2::num / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::num, _Period::num)) * (_Period::den / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::den, _Period::den))), ((_Period2::den / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::den, _Period::den)) * (_Period::num / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::num, _Period::num)))>::den == 1)> [with _Period2 = _Period2; _Rep = _Rep; _Period = _Period]’:
/usr/include/c++/10/chrono:473:154:   required from here
/usr/include/c++/10/chrono:428:27: internal compiler error: 段错误
  428 |  _S_gcd(intmax_t __m, intmax_t __n) noexcept
      |                           ^~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
error: command '/usr/local/cuda-11.2/bin/nvcc' failed with exit status 1

**Comment by resuly** [comment]
> @resuly, could you please check the shape of `x` (both `coords` and `feats`) before the line of `x0 = self.stem(x)`?

Sorry for the late reply. It should be the same zero inputs issue as @noahstier mentioned above.

**Comment by zhijian-liu** [comment]
@resuly, in this case, you should check what the input size is (before sending into the model). You need to make sure the input has more than one point.

**Comment by zhijian-liu** [comment]
Since TorchSparse has been upgraded to v2.1.0, could you please attempt to install the latest version? I will now close this issue, but please don't hesitate to reopen it if the problem persists.
